spring.application.name=poll
server.port=6767
#DATABASE
spring.datasource.url=jdbc:mysql://localhost:8080/poll_db
spring.datasource.username=root
spring.datasource.password=Sakshi@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
